name: diacritic
description: >
    Removes common accents and diacritical signs from a
    string by replacing them with an equivalent character.
version: 0.0.2
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/diacritic

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
